{"level":"info","msg":"Wrapper started","time":"2021-04-21T00:21:50.680Z","wrapper":266}
{"level":"info","msg":"finding gitaly","pid_file":"/var/opt/gitlab/gitaly/gitaly.pid","time":"2021-04-21T00:21:50.682Z","wrapper":266}
{"level":"info","msg":"spawning a process","time":"2021-04-21T00:21:50.683Z","wrapper":266}
{"gitaly":276,"level":"info","msg":"monitoring gitaly","time":"2021-04-21T00:21:50.690Z","wrapper":266}
time="2021-04-21T00:21:52Z" level=info msg="Starting GitalyversionGitaly, version 13.10.3"
time="2021-04-21T00:21:52Z" level=warning msg="git path not configured. Using default path resolution" resolvedPath=/opt/gitlab/embedded/bin/git
time="2021-04-21T00:21:52Z" level=info msg="clearing disk cache object folder" path=/var/opt/gitlab/git-data/repositories
time="2021-04-21T00:21:52Z" level=info msg="moving disk cache object folder to /var/opt/gitlab/git-data/repositories/+gitaly/tmp/diskcache036394452" path=/var/opt/gitlab/git-data/repositories
time="2021-04-21T00:21:52Z" level=info msg="disk cache object folder doesn't exist, no need to remove" path=/var/opt/gitlab/git-data/repositories
time="2021-04-21T00:21:52Z" level=info msg="Starting file walker for /var/opt/gitlab/git-data/repositories/+gitaly/cache" path=/var/opt/gitlab/git-data/repositories/+gitaly/cache
time="2021-04-21T00:21:52Z" level=info msg="Starting file walker for /var/opt/gitlab/git-data/repositories/+gitaly/state" path=/var/opt/gitlab/git-data/repositories/+gitaly/state
time="2021-04-21T00:21:52Z" level=info msg="cleared all cache object files in /var/opt/gitlab/git-data/repositories/+gitaly/tmp/diskcache036394452 after 49.192Âµs" path=/var/opt/gitlab/git-data/repositories
{"level":"info","msg":"finished tempdir cleaner walk","storage":"default","time":"2021-04-21T00:21:56.297Z","time_ms":0}
{"level":"warning","msg":"spawned","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","276","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","supervisor.pid":298,"time":"2021-04-21T00:21:56.318Z"}
{"level":"warning","msg":"spawned","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","276","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","supervisor.pid":299,"time":"2021-04-21T00:21:56.323Z"}
{"level":"info","msg":"starting RSS monitor","supervisor.name":"gitaly-ruby.0","supervisor.rss_threshold":209715200,"time":"2021-04-21T00:21:56.347Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:21:56.360Z"}
{"level":"info","msg":"starting RSS monitor","supervisor.name":"gitaly-ruby.1","supervisor.rss_threshold":209715200,"time":"2021-04-21T00:21:56.360Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:21:56.385Z"}
{"address":"/var/opt/gitlab/gitaly/gitaly.socket","level":"info","msg":"listening at unix address","time":"2021-04-21T00:21:56.485Z"}
{"address":"/var/opt/gitlab/gitaly/internal_sockets/internal.sock","level":"info","msg":"listening at unix address","time":"2021-04-21T00:21:56.516Z"}
{"address":"localhost:9236","level":"info","msg":"starting prometheus listener","time":"2021-04-21T00:21:56.539Z"}
{"level":"info","msg":"maintenance: daily scheduled","pid":276,"scheduled":"2021-04-21T12:00:00Z","time":"2021-04-21T00:21:56.540Z"}
{"level":"info","msg":"PID 298 BUNDLE_GEMFILE=/opt/gitlab/embedded/service/gitaly-ruby/Gemfile","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","276","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","time":"2021-04-21T00:22:02.665Z"}
{"level":"info","msg":"PID 299 BUNDLE_GEMFILE=/opt/gitlab/embedded/service/gitaly-ruby/Gemfile","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","276","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-04-21T00:22:02.714Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:22:11.391Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:22:11.393Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:22:26.401Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:22:26.401Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:22:41.404Z"}
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: connect: connection refused\". Reconnecting...","pid":276,"system":"system","time":"2021-04-21T00:22:41.404Z"}
{"correlation_id":"d4f8560f0748b62f81fd6b2279b355e4","grpc.code":"OK","grpc.meta.auth_version":"v2","grpc.meta.client_name":"gitlab-sidekiq","grpc.meta.deadline_type":"unknown","grpc.method":"Check","grpc.request.deadline":"2021-04-21T01:20:19.004Z","grpc.request.fullMethod":"/grpc.health.v1.Health/Check","grpc.service":"grpc.health.v1.Health","grpc.start_time":"2021-04-21T01:20:09.944Z","grpc.time_ms":0.021,"level":"info","msg":"finished unary call with code OK","peer.address":"@","pid":276,"span.kind":"server","system":"grpc","time":"2021-04-21T01:20:09.944Z"}
{"level":"info","msg":"finished tempdir cleaner walk","storage":"default","time":"2021-04-21T01:21:56.298Z","time_ms":0}
{"correlation_id":"a5966ec5c311e9afe80b1488f4b09a21","grpc.code":"OK","grpc.meta.auth_version":"v2","grpc.meta.client_name":"gitlab-sidekiq","grpc.meta.deadline_type":"unknown","grpc.method":"Check","grpc.request.deadline":"2021-04-21T02:20:23.001Z","grpc.request.fullMethod":"/grpc.health.v1.Health/Check","grpc.service":"grpc.health.v1.Health","grpc.start_time":"2021-04-21T02:20:13.161Z","grpc.time_ms":1.937,"level":"info","msg":"finished unary call with code OK","peer.address":"@","pid":276,"span.kind":"server","system":"grpc","time":"2021-04-21T02:20:13.163Z"}
{"level":"info","msg":"finished tempdir cleaner walk","storage":"default","time":"2021-04-21T02:21:56.298Z","time_ms":0}
{"correlation_id":"e77fa9dd782c1b86dc8fc21458893501","grpc.code":"OK","grpc.meta.auth_version":"v2","grpc.meta.client_name":"gitlab-sidekiq","grpc.meta.deadline_type":"unknown","grpc.method":"Check","grpc.request.deadline":"2021-04-21T03:20:27.004Z","grpc.request.fullMethod":"/grpc.health.v1.Health/Check","grpc.service":"grpc.health.v1.Health","grpc.start_time":"2021-04-21T03:20:17.774Z","grpc.time_ms":0.026,"level":"info","msg":"finished unary call with code OK","peer.address":"@","pid":276,"span.kind":"server","system":"grpc","time":"2021-04-21T03:20:17.775Z"}
{"level":"info","msg":"finished tempdir cleaner walk","storage":"default","time":"2021-04-21T03:21:56.299Z","time_ms":0}
{"gitaly":276,"level":"warning","msg":"forwarding signal","signal":18,"time":"2021-04-21T03:54:19.064Z","wrapper":266}
{"gitaly":276,"level":"warning","msg":"forwarding signal","signal":15,"time":"2021-04-21T03:54:19.075Z","wrapper":266}
{"error":"signal: killed","level":"warning","msg":"exited","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","276","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","time":"2021-04-21T03:54:19.102Z"}
{"error":"signal: killed","level":"warning","msg":"exited","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","276","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2021-04-21T03:54:19.133Z"}
{"level":"warning","msg":"transport: http2Server.HandleStreams failed to read frame: read unix /var/opt/gitlab/gitaly/gitaly.socket-\u003e@: use of closed network connection","pid":276,"system":"system","time":"2021-04-21T03:54:19.134Z"}
{"level":"warning","msg":"transport: http2Server.HandleStreams failed to read frame: read unix /var/opt/gitlab/gitaly/internal_sockets/internal.sock-\u003e@: use of closed network connection","pid":276,"system":"system","time":"2021-04-21T03:54:19.134Z"}
{"error":"received signal \"terminated\"","level":"error","msg":"shutting down","time":"2021-04-21T03:54:19.134Z"}
{"level":"info","msg":"Gitaly stopped","time":"2021-04-21T03:54:19.134Z"}
{"gitaly":276,"level":"warning","msg":"forwarding signal","signal":17,"time":"2021-04-21T03:54:19.136Z","wrapper":266}
{"gitaly":276,"level":"error","msg":"wrapper for gitaly shutting down","time":"2021-04-21T03:54:19.848Z","wrapper":266}
